# Welcome to Jekyll!
#

# Site settings
title: Ubicrypt
description: |
  Encrypt and replicate your data in the cloud

  Safely
owner: Giancarlo Frison # or company name
first_published: 2016 # if migrating another site, the year of your first publish
email: giancarlo@gfrison.com
baseurl: "/ubicrypt" # the subpath of your site, e.g. /blog
url: "http://gfrison.github.io" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/gfrison
  github: https://github.com/gfrison
  linkedin-square: https://linkedin.com/in/gfrison
  #facebook-official: https://facebook.com/gfrison
  #google-plus-square: https://plus.google.com/u/0/+<username>
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
